appchain/src/lib.rs
appchain/src/mainchain.rs

Add configure for rpc

---

appchain/src/lib.rs

fix bug when unlock or mint failed

Fix bug when unlock or mint failed

---

lpos/src/lib.rs

Fix error when get exclude-validators.

Fix error when get exclude-validators

---

appchain/src/lib.rs
appchain/src/mainchain.rs

Retry with failsafe endpoint

---

appchain/Cargo.toml
appchain/src/lib.rs
lpos/Cargo.toml

Improve submit observations

---

appchain/src/lib.rs
appchain/src/mock.rs
appchain/src/tests.rs

Add set_asset_name function for appchain.

Add set_asset_name function for appchain.

---

appchain/src/lib.rs
appchain/src/mainchain.rs

Add transfer-from-pallet function for 0.9.13

Add transfer-from-pallet function for 0.9.13

---

appchain/src/lib.rs

* fix problem about NotificationHistory
* add sequence for asset-burn-event

Add more information to transfer error detection

---

appchain/src/lib.rs

Fix problem about NotificationHistory

Fix problem about NotificationHistory

---

.cargo/config.toml
appchain/src/benchmarking.rs
appchain/src/tests.rs
lpos/src/lib.rs
lpos/src/mock.rs
support/src/lib.rs
upward-messages/src/lib.rs
upward-messages/src/tests.rs

- Add .cargo/config.toml by https://github.com/paritytech/substrate/pull/10570
- fix run `cargo clippy` waring
- fix run `cargo clippy --all-targets --all-features --tests --benches -- -D warnings` waring

Fix clippy warring

---

appchain/src/lib.rs
appchain/src/mainchain.rs

refactor support nft

---

appchain/src/lib.rs

Add storage migration for appchain-pallet

---

appchain/src/lib.rs

Add sequence for mint asset

---

appchain/src/traits_default_impl.rs

Convert rmrk base metadata(https://github.com/rmrk-team/rmrk-spec/blob/master/standards/rmrk2.0.0/entities/metadata.md#schema-definition) to nep171 metadata.

Add convertor for support rmrk base metadata to nep171

---

Makefile
appchain/benchmarking/Cargo.toml
appchain/benchmarking/src/lib.rs
appchain/src/lib.rs
lpos/src/lib.rs
support/src/types.rs
upward-messages/src/lib.rs

- Remove alloc to import String and ToString, replace by scale-info import this.
- add check-no-std Makefile

Remove alloc

---

appchain/src/lib.rs

This PR is used to fix the problem of verifying current validators in the case of h160 in function submit_observations.

Use (public)key data to query the session key owner in all places

---

appchain/src/lib.rs
appchain/src/mainchain.rs

The update in this PR are as follows:
- add  force-set-notification-id;
- modify notification to match update in anchor.

Minor changes to simplify the next upgrade of near contract.

---

appchain/src/lib.rs
appchain/src/mock.rs
appchain/src/tests.rs
lpos/src/lib.rs
lpos/src/mock.rs
upward-messages/src/lib.rs

1. Fix test case to make it works.
2. Changes storage's visible .

Fix test case and changes storage's visible.

---

appchain/src/lib.rs

 Minor refactor

---

bridge/src/lib.rs
bridge/src/migration.rs

add storage migration for bridge

Migrate AssetIdByTokenId from octopus-appchain

---

upward-messages/src/lib.rs

Modify default value of interval and add migration in upward-messages

Modify default value of interval and add migration in upward-messages

---

bridge/src/lib.rs
bridge/src/nep141.rs
bridge/src/nonfungible.rs
bridge/src/tests.rs
bridge/src/token.rs
support/src/types.rs
upward-messages/src/migrations.rs

Support claim expenses for relayer

Support to pay transfer fee for relayer

---

appchain/src/mainchain.rs
appchain/src/tests.rs

Change Params's account_id and args_base64 to String type

Fix http request response

---

appchain/build.rs
appchain/src/lib.rs

relate issue: https://github.com/paritytech/subxt/pull/776

Update get git-version way

---

bridge/src/lib.rs
bridge/src/tests.rs

Add test for set_coef_for_calculate_fee

Add test for set_coef_for_calculate_fee

---

Cargo.toml
appchain/Cargo.toml
appchain/benchmarking/Cargo.toml
bridge/Cargo.toml
bridge/benchmarking/Cargo.toml
lpos/Cargo.toml
support/Cargo.toml
upward-messages/Cargo.toml

https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds

use workspace dependencies
